colorScheme = "slate"
defaultAppearance = "dark"
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true
enableA11y = false
enableStructuredBreadcrumbs = true

fingerprintAlgorithm = "sha512"

[header]
  layout = "fixed-fill-blur"

[footer]
  showMenu = false
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 3
  showMoreLink = true
  showMoreLinkDest = "/projects/"
  cardView = true
  cardViewScreenWidth = true
  layoutBackgroundBlur = true

[article]
  showDate = true
  showViews = false
  showLikes = false
  showAuthor = false
  showHero = true
  heroStyle = "big"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showDraftLabel = false
  showEdit = false
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = true
  showCategories = false
  showTags = true
  showAuthorsBadges = false
  showWordCount = false
  showZenMode = false

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showSummary = true
  showCards = true
  orderByWeight = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = true
  constrainItemsWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = false
  layoutBackgroundBlur = true
  showBreadcrumbs = true
  showTableOfContents = false
  cardView = true

[term]
  showHero = false
  layoutBackgroundBlur = true
  showBreadcrumbs = true
  showTableOfContents = false
  cardView = true
